### PR TITLE
fix: export typings from src

### LINKED ISSUE #593: specialChars object is undefined when imported
- `@testing-library/dom` version: 7.30.0
- `@testing-library/user-event` version: 13.0.1
- `typescript` version: 4.2.3

`index.ts`:

```typescript
import { specialChars } from "@testing-library/user-event";

console.log(specialChars);
```

**What happened:**
- TypeScript error: `TS1361: 'specialChars' cannot be used as a value because it was imported using 'import type'.`
- Console log returned `undefined`

Reproduction repository: https://codesandbox.io/s/unruffled-river-ps0i7

**Problem description:**
When I try to import `specialChars` from `@testing-library/user-event`, its value is `undefined`.

### LINKED ISSUE #594: Click, keyboard & type TypeScript types are resolved as "any" because of wrong imports in typings
- `@testing-library/dom` version: 7.30.0
- `@testing-library/user-event` version: 13.0.1
- `typescript` version: 4.2.3

**Problem description:**
The file `typings/index.d.ts` contains type imports from `../src/` folder, which does not exist in the distributed package, so all those types are resolved to `any`.

Codesandbox: https://codesandbox.io/s/romantic-shadow-uio28

image

`typings/index.d.ts` in the corresponding `node_modules` folder:

image

This concerns the following types:

- click, clickOptions
- keyboard, keyboardOptions, keyboardKey,
- type, typeOptions

### PR DESCRIPTION
**Pull request by ph-fritsche**
**What**:

Export typings from `src`.
Fix missing exported `specialChars` object.

**Why**:

Closes #594 
Closes #593 

**How**:

Remove `typings`.
Convert `src/index.js` to Typescript and add typings for exported JS modules in `src`.

**Checklist**:

- N/A Documentation
- N/A Tests
- [x] Typings
- [x] Ready to be merged

### CODE REVIEW

**Comment by nstepien** [comment]
This is making things worse for us, for example:
```
src/...test.tsx:271:15 - error TS2554: Expected 2-3 arguments, but got 1.

271     userEvent.click(screen.getByLabelText(/only show changes/i));
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  node_modules/@testing-library/user-event/dist/click.d.ts:1:37
    1 export function click(element: any, init: any, { skipHover, clickCount }?: {
                                          ~~~~~~~~~
    An argument for 'init' was not provided.
```
Same issue for `hover`, `unhover`, `dblClick`, and more.
`TargetElement` used to be exported but not anymore.

**Comment by ph-fritsche** [comment]
@nstepien Thanks for the report.
Rollup removed the types from `lib.dom.d.ts` :facepalm:

**Comment by ph-fritsche** [comment]
@nstepien Could you have a look at #599  ?

**Comment by ph-fritsche** [comment]
Check out [v13.0.4](https://github.com/testing-library/user-event/releases/tag/v13.0.4) :rocket:

**Comment by riboher** [comment]
Hi there! Issue with exporting `TargetElement` is still happening after updating to v13.0.7 😞 . Typescript is complaining about `TargetElement` not being exported in `@testing-library/user-event`

**Comment by ph-fritsche** [comment]
@riboher Yes, `TargetElement` is completely removed.
It was `Element | Window` and used in multiple places, where the actual typings were different. It won't come back.

What have you been using it for?

**Comment by riboher** [comment]
Oh! Ok! Good to know then. Just needed it for typing one of my tests and make sure a `nextSibling` was correctly typed for an upload event. You say I can try with `Element` then? Thanks!

**Comment by ph-fritsche** [comment]
https://github.com/testing-library/user-event/blob/4c3d3cf4eaf7c162a519148f85e6b58bf8905304/src/upload.ts#L16-L17
